application: matkatoistin
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /favicon\.ico
  static_files: html/images/favicon.ico
  upload: html/images/favicon\.ico
    
- url: /css
  static_dir: html/css
  
- url: /js
  static_dir: html/js

- url: /img/
  static_dir: html/img

- url: /admin.*
  script: AdminPage.application
  login: admin
  
- url: /queue.*
  script: QueuePage.application
  login: admin
  
- url: /.*
  script: MainPage.application

libraries:
- name: jinja2
  version: latest
